#!/bin/bash
#
# Copyright(C) 2014, Krisztián Kende <nemh@freemail.hu>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

if [[ $UID == 0 ]]
then systemback
else
  tmpxauth=/tmp/sbXauthority-$RANDOM$RANDOM

  if [[ "$XAUTHORITY" ]]
  then cp -a "$XAUTHORITY" $tmpxauth
  elif [[ -f ~/.Xauthority ]]
  then cp -a ~/.Xauthority $tmpxauth
  else
    if which zenity >/dev/null
    then zenity --title=Systemback --error --text="Failed to start Systemback graphical user interface!\n\nCannot connect to X server."
    else kdialog --title=Systemback --error="Failed to start Systemback graphical user interface!\n\nCannot connect to X server."
    fi

    exit 1
  fi

  XAUTHORITY=$tmpxauth sudo -nH $1 /usr/bin/systemback authorization $USER
  rm -rf $tmpxauth
fi
